from dotenv import load_dotenv
from langchain.prompts.prompt import PromptTemplate
from langchain_openai import ChatOpenAI
from langchain.chains import LLMChain

from output_parsers import summary_parser
from third_parties.linkedin import scrape_linkedin_profile
from agents.linkedin_lookup_agent import lookup as linkedin_lookup_agent
from agents.twitter_lookup_agent import lookup as twitter_lookup_agent
from third_parties.twitter import scrape_user_tweets


def ice_break_with(name: str) -> str:
    linkedin_username = linkedin_lookup_agent(name=name)
    linkedin_data = scrape_linkedin_profile(
        linkedin_profile_url=linkedin_username, mock=True
    )

    twitter_username = twitter_lookup_agent(name=name)
    tweets = scrape_user_tweets(username=twitter_username, mock=True)

    summary_template = """
    given the information about a person from linkedin {information},
    and their latest twitter posts {twitter_posts} I want you to create:
    1. A short summary
    2. two interesting facts about them 

    Use both information from twitter and Linkedin
    \n{format_instructions}
    """
    summary_prompt_template = PromptTemplate(
        input_variables=["information", "twitter_posts"],
        template=summary_template,
        partial_variables={
            "format_instructions": summary_parser.get_format_instructions()
        },
    )

    llm = ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo")

    chain = summary_prompt_template | llm | summary_parser

    res = chain.invoke(input={"information": linkedin_data, "twitter_posts": tweets})

    print(res)


if __name__ == "__main__":
    load_dotenv()

    print("Ice Breaker Enter")
    ice_break_with(name="Eden Marco")
# got below response:
# Ice Breaker Enter
#
#
# > Entering new AgentExecutor chain...
# I need to find the Linkedin profile page for Eden Marco.
# Action: Crawl Google 4 linkedin profile page
# Action Input: Eden Marco[{'url': 'https://il.linkedin.com/in/eden-marco', 'content': "Others named Eden Marco\nEden Marco\nStrategy Analyst at Deloitte\nEden Marco\nMD Candidate, University of Toronto\nEden Marco\nDoctor of Optometry Candidate\nEden Marco\n--\n7 others named Eden Marco are on LinkedIn\nAdd new skills with these courses\nChoosing a Database: PostgreSQL, MySQL, Mongo, and Cloud\nDeploying Django Apps: Make Your Site Go Live\nAWS 🛒\nCome by the AI21 Labs booth to talk to our team about how #GenAI can reshape the retail…\nExperience & Education\nGoogle\n*** ****, ******** *********** - ****** *****\n*****\n*********** ***** **********\n**** ********\n****** ******** ********\n******** - ****** ********* ** **********\n********’* Eden Marco\nTel Aviv District, Israel\n4K followers\n500+ connections\nView mutual connections with Eden\nWelcome back\nor\nBy clicking Continue, you agree to LinkedIn’s User Agreement, Privacy Policy, and Cookie Policy.\n We're currently hiring for various positions at\xa0Chaos Labs\xa0and are seeking talented individuals to come to work with us 🥇\nCheck…\nBootstrapped SaaS doing $1M ARR:\n- 1 Founder\n- 1 Developer\n- 1 Customer Support\n- 1/2 Marketer\nVC-funded SaaS doing $1M ARR:\nThe future of retail is getting personal. Join now\nAbout\nWelcome back\nor\nBy clicking Continue, you agree to LinkedIn’s User Agreement, Privacy Policy, and Cookie Policy.\n"}, {'url': 'https://www.udemy.com/user/eden-marco/', 'content': 'BSC in Computer Science from the Technion - Israel Institute of Technology. I have always been a fan of teaching and mentorship and I am teaching CS courses (Functional Programming and Introduction to CS) at Reichman University, Israel. Eden Marco is a Udemy instructor with educational courses available for enrollment. Check out the latest ...'}, {'url': 'https://www.youtube.com/c/EdenMarco', 'content': 'Share your videos with friends, family, and the world'}, {'url': 'https://www.udemy.com/course/langchain/', 'content': 'Eden Marco | LLM Specialist. Best Selling Instructor. 4.6 Instructor Rating. 16,282 Reviews. 71,149 Students. 7 Courses. I am a passionate Software Engineer with years of experience in back-end development, one of the first engineers at Orca Security, and now I am working as a Customer Engineer at Google Cloud.'}, {'url': 'https://www.linkedin.com/posts/eden-marco_one-of-my-favorite-things-about-being-a-udemy-activity-7176269229858381826-7U6d', 'content': 'Eden Marco LLMs @ Google Cloud | Best-selling Udemy Instructor | Backend & GenAI 1w Report this post Contextual Answers from the AI21 Labs team is a fantastic model when you want the LLM to always ...'}]
# https://il.linkedin.com/in/eden-marcoI have found the Linkedin profile page for Eden Marco.
# Final Answer: https://il.linkedin.com/in/eden-marco
#
# > Finished chain.
#
#
# > Entering new AgentExecutor chain...
# I should start by searching for the Twitter profile page of Eden Marco.
# Action: Crawl Google 4 Twitter profile page
# Action Input: Eden Marco Twitter[{'url': 'https://twitter.com/EdenEmarco177/status/1659558174121250816', 'content': "🧵 Ever wanted to talk with your LLM🤖 on some custom data that it wasn't originally trained on? @LangChainAI 🦜🔗+ @pinecone 🌲vectorstore will do all the heavy lifting for you."}, {'url': 'https://twitter.com/EdenEmarco177/status/1670064667643740164', 'content': '14/15 I teach @LangChainAI 🦜🔗 elaborately in my @udemy course with almost 5k students and 630+ reviews https://udemy.com/course/langchain/…'}, {'url': 'https://twitter.com/EdenEmarco177/status/1670064674581225474', 'content': '15/15 What are your best @LangChainAI🦜🔗 chunking strategies? would love to hear your thought😎😎😎 @pinecone 🌲 Would love to hear your take on this as well.'}, {'url': 'https://il.linkedin.com/in/eden-marco', 'content': "Others named Eden Marco\nEden Marco\nStrategy Analyst at Deloitte\nEden Marco\nMD Candidate, University of Toronto\nEden Marco\nDoctor of Optometry Candidate\nEden Marco\n--\n7 others named Eden Marco are on LinkedIn\nAdd new skills with these courses\nChoosing a Database: PostgreSQL, MySQL, Mongo, and Cloud\nDeploying Django Apps: Make Your Site Go Live\nAWS 🛒\nCome by the AI21 Labs booth to talk to our team about how #GenAI can reshape the retail…\nExperience & Education\nGoogle\n*** ****, ******** *********** - ****** *****\n*****\n*********** ***** **********\n**** ********\n****** ******** ********\n******** - ****** ********* ** **********\n********’* Eden Marco\nTel Aviv District, Israel\n4K followers\n500+ connections\nView mutual connections with Eden\nWelcome back\nor\nBy clicking Continue, you agree to LinkedIn’s User Agreement, Privacy Policy, and Cookie Policy.\n We're currently hiring for various positions at\xa0Chaos Labs\xa0and are seeking talented individuals to come to work with us 🥇\nCheck…\nBootstrapped SaaS doing $1M ARR:\n- 1 Founder\n- 1 Developer\n- 1 Customer Support\n- 1/2 Marketer\nVC-funded SaaS doing $1M ARR:\nThe future of retail is getting personal. Join now\nAbout\nWelcome back\nor\nBy clicking Continue, you agree to LinkedIn’s User Agreement, Privacy Policy, and Cookie Policy.\n"}, {'url': 'https://github.com/emarco177/', 'content': 'A repository for learning LangChain🦜🔗 by building a generative ai application. This is a web application crawling Linkedin & Twitter data about a person and customizes an ice breaker with them.'}]
# https://twitter.com/EdenEmarco177/status/1659558174121250816I found the Twitter profile page for Eden Marco, now I need to extract their username.
# Action: Extract username from Twitter URL
# Action Input: https://twitter.com/EdenEmarco177/status/1659558174121250816Extract username from Twitter URL is not a valid tool, try one of [Crawl Google 4 Twitter profile page].I need to go back and use the Crawl Google 4 Twitter profile page tool to find the username.
# Action: Crawl Google 4 Twitter profile page
# Action Input: Eden Marco Twitter[{'url': 'https://twitter.com/EdenEmarco177/status/1663406962820763649', 'content': 'Super excited to invite to THE Generative AI 🤖 developers event- a 2 hour evening meetup hosted by @googlecloud featuring @pinecone at June 7th We will focus on @LangChainAI 🦜🔗 and engage technical engineering discussions around vectorstores'}, {'url': 'https://twitter.com/EdenEmarco177/status/1659558174121250816', 'content': "🧵 Ever wanted to talk with your LLM🤖 on some custom data that it wasn't originally trained on? @LangChainAI 🦜🔗+ @pinecone 🌲vectorstore will do all the heavy lifting for you."}, {'url': 'https://twitter.com/EdenEmarco177/status/1670064631560151040', 'content': "2/14 Chunking is the process of splitting long pieces of text into smaller, hopefully semantically meaningful chunks. It's essential when dealing with large text inputs, as LLMs often have limitations on the amount of tokens that can be processed at once."}, {'url': 'https://il.linkedin.com/in/eden-marco', 'content': "Others named Eden Marco\nEden Marco\nStrategy Analyst at Deloitte\nEden Marco\nMD Candidate, University of Toronto\nEden Marco\nDoctor of Optometry Candidate\nEden Marco\n--\n7 others named Eden Marco are on LinkedIn\nAdd new skills with these courses\nChoosing a Database: PostgreSQL, MySQL, Mongo, and Cloud\nDeploying Django Apps: Make Your Site Go Live\nAWS 🛒\nCome by the AI21 Labs booth to talk to our team about how #GenAI can reshape the retail…\nExperience & Education\nGoogle\n*** ****, ******** *********** - ****** *****\n*****\n*********** ***** **********\n**** ********\n****** ******** ********\n******** - ****** ********* ** **********\n********’* Eden Marco\nTel Aviv District, Israel\n4K followers\n500+ connections\nView mutual connections with Eden\nWelcome back\nor\nBy clicking Continue, you agree to LinkedIn’s User Agreement, Privacy Policy, and Cookie Policy.\n We're currently hiring for various positions at\xa0Chaos Labs\xa0and are seeking talented individuals to come to work with us 🥇\nCheck…\nBootstrapped SaaS doing $1M ARR:\n- 1 Founder\n- 1 Developer\n- 1 Customer Support\n- 1/2 Marketer\nVC-funded SaaS doing $1M ARR:\nThe future of retail is getting personal. Join now\nAbout\nWelcome back\nor\nBy clicking Continue, you agree to LinkedIn’s User Agreement, Privacy Policy, and Cookie Policy.\n"}, {'url': 'https://www.youtube.com/c/EdenMarco', 'content': 'Share your videos with friends, family, and the world'}]
# https://twitter.com/EdenEmarco177/status/1663406962820763649I found the Twitter profile page for Eden Marco, now I need to extract their username.
# Action: Look for username on Twitter profile page
# Action Input: https://twitter.com/EdenEmarco177/status/1663406962820763649Look for username on Twitter profile page is not a valid tool, try one of [Crawl Google 4 Twitter profile page].I need to go back and use the Crawl Google 4 Twitter profile page tool to find the username.
# Action: Crawl Google 4 Twitter profile page
# Action Input: Eden Marco Twitter[{'url': 'https://twitter.com/EdenEmarco177/status/1663406962820763649', 'content': 'Super excited to invite to THE Generative AI 🤖 developers event- a 2 hour evening meetup hosted by @googlecloud featuring @pinecone at June 7th We will focus on @LangChainAI 🦜🔗 and engage technical engineering discussions around vectorstores'}, {'url': 'https://twitter.com/edendimarco', 'content': 'Log in. Sign up'}, {'url': 'https://twitter.com/EdenEmarco177/status/1670064667643740164', 'content': '14/15 I teach @LangChainAI 🦜🔗 elaborately in my @udemy course with almost 5k students and 630+ reviews https://udemy.com/course/langchain/…'}, {'url': 'https://www.udemy.com/course/langchain/', 'content': 'Created by Eden Marco | LLM Specialist. Last updated 7/2024. English. ... Ice Breaker- LangChain agent that given a name, searches in google to find Linkedin and twitter profiles, scrape the internet for information about a name you provide and generate a couple of personalized ice breakers to kick off a conversation with the person.'}, {'url': 'https://www.linkedin.com/posts/eden-marco_its-about-time-introducing-activity-7109750234959818752-NV2k', 'content': "Better Resistance against prompt injection attacks\nCheckout the LangChain ðŸ¦œðŸ”— usage:\nhttps://lnkd.in/dAMu-m6A\nBig shoutout to Oleksandr Yaremchuk and Neal Swaelens ðŸ™Œ\nExperienced security professional managing AI in regulated environments\nThis seems more like DLP than actual security.\n Over the past few months, there's been a tremendous push in refactoring their framework, all aimed at providing an infrastructure that's geared towards building more secure and reliable apps\nDisclaimer: The thoughts and opinions shared here are entirely my own and do not represent those of my employer or any other affiliated organizations.\n Global Gen AI CoE Leader | AI & DS Senior Manager\nHugh Bethell Vaibhav Chadha Luis Esgueva MariÃ±o\nTo view or add a comment, sign in\nMore Relevant Posts\nLLM Lead @ Colin Fraser | @colin-fraser.net on bsky (@colin_fraser) on X\nTo view or add a comment, sign in\nEden Marco reposted this\nDirector of AI Innovation at Orca Security ðŸš€ 2x Why is it a MUST-HAVE for using LLMs in production?\n- ðŸ›¡ Sanitization\n- ðŸš« Harmful language detection\n- ðŸ•µâ™€ï¸� Data leakage prevention\n- ðŸ’ª"}]
# https://twitter.com/EdenEmarco177/status/1663406962820763649I found the Twitter profile page for Eden Marco, now I need to extract their username.
# Action: Extract username from Twitter URL
# Action Input: https://twitter.com/EdenEmarco177/status/1663406962820763649Extract username from Twitter URL is not a valid tool, try one of [Crawl Google 4 Twitter profile page].I need to find a different approach to extract the username from the Twitter profile page.
# Action: Crawl Google 4 Twitter profile page
# Action Input: Eden Marco Twitter[{'url': 'https://twitter.com/EdenEmarco177/status/1663406962820763649', 'content': 'Super excited to invite to THE Generative AI 🤖 developers event- a 2 hour evening meetup hosted by @googlecloud featuring @pinecone at June 7th We will focus on @LangChainAI 🦜🔗 and engage technical engineering discussions around vectorstores'}, {'url': 'https://twitter.com/EdenEmarco177/status/1670064667643740164', 'content': '14/15 I teach @LangChainAI 🦜🔗 elaborately in my @udemy course with almost 5k students and 630+ reviews https://udemy.com/course/langchain/…'}, {'url': 'https://twitter.com/EdenEmarco177/status/1659558174121250816', 'content': "🧵 Ever wanted to talk with your LLM🤖 on some custom data that it wasn't originally trained on? @LangChainAI 🦜🔗+ @pinecone 🌲vectorstore will do all the heavy lifting for you."}, {'url': 'https://il.linkedin.com/in/eden-marco', 'content': "Others named Eden Marco\nEden Marco\nStrategy Analyst at Deloitte\nEden Marco\nMD Candidate, University of Toronto\nEden Marco\nDoctor of Optometry Candidate\nEden Marco\n--\n7 others named Eden Marco are on LinkedIn\nAdd new skills with these courses\nChoosing a Database: PostgreSQL, MySQL, Mongo, and Cloud\nDeploying Django Apps: Make Your Site Go Live\nAWS 🛒\nCome by the AI21 Labs booth to talk to our team about how #GenAI can reshape the retail…\nExperience & Education\nGoogle\n*** ****, ******** *********** - ****** *****\n*****\n*********** ***** **********\n**** ********\n****** ******** ********\n******** - ****** ********* ** **********\n********’* Eden Marco\nTel Aviv District, Israel\n4K followers\n500+ connections\nView mutual connections with Eden\nWelcome back\nor\nBy clicking Continue, you agree to LinkedIn’s User Agreement, Privacy Policy, and Cookie Policy.\n We're currently hiring for various positions at\xa0Chaos Labs\xa0and are seeking talented individuals to come to work with us 🥇\nCheck…\nBootstrapped SaaS doing $1M ARR:\n- 1 Founder\n- 1 Developer\n- 1 Customer Support\n- 1/2 Marketer\nVC-funded SaaS doing $1M ARR:\nThe future of retail is getting personal. Join now\nAbout\nWelcome back\nor\nBy clicking Continue, you agree to LinkedIn’s User Agreement, Privacy Policy, and Cookie Policy.\n"}, {'url': 'https://www.youtube.com/c/EdenMarco', 'content': 'Share your videos with friends, family, and the world'}]
# https://twitter.com/EdenEmarco177/status/1663406962820763649I should try to manually extract the username from the Twitter profile page URL.
# Action: Manually extract username from Twitter URL
# Action Input: https://twitter.com/EdenEmarco177/status/1663406962820763649Manually extract username from Twitter URL is not a valid tool, try one of [Crawl Google 4 Twitter profile page].I need to go back and use the Crawl Google 4 Twitter profile page tool to find the username.
# Action: Crawl Google 4 Twitter profile page
# Action Input: Eden Marco Twitter[{'url': 'https://twitter.com/EdenEmarco177/status/1659558174121250816', 'content': "🧵 Ever wanted to talk with your LLM🤖 on some custom data that it wasn't originally trained on? @LangChainAI 🦜🔗+ @pinecone 🌲vectorstore will do all the heavy lifting for you."}, {'url': 'https://twitter.com/EdenEmarco177/status/1670064667643740164', 'content': '14/15 I teach @LangChainAI 🦜🔗 elaborately in my @udemy course with almost 5k students and 630+ reviews https://udemy.com/course/langchain/…'}, {'url': 'https://twitter.com/EdenEmarco177/status/1670064674581225474', 'content': '15/15 What are your best @LangChainAI🦜🔗 chunking strategies? would love to hear your thought😎😎😎 @pinecone 🌲 Would love to hear your take on this as well.'}, {'url': 'https://twitter.com/EdenEmarco177/status/1670064631560151040', 'content': "2/14 Chunking is the process of splitting long pieces of text into smaller, hopefully semantically meaningful chunks. It's essential when dealing with large text inputs, as LLMs often have limitations on the amount of tokens that can be processed at once."}, {'url': 'https://il.linkedin.com/in/eden-marco', 'content': "Others named Eden Marco\nEden Marco\nStrategy Analyst at Deloitte\nEden Marco\nMD Candidate, University of Toronto\nEden Marco\nDoctor of Optometry Candidate\nEden Marco\n--\n7 others named Eden Marco are on LinkedIn\nAdd new skills with these courses\nChoosing a Database: PostgreSQL, MySQL, Mongo, and Cloud\nDeploying Django Apps: Make Your Site Go Live\nAWS 🛒\nCome by the AI21 Labs booth to talk to our team about how #GenAI can reshape the retail…\nExperience & Education\nGoogle\n*** ****, ******** *********** - ****** *****\n*****\n*********** ***** **********\n**** ********\n****** ******** ********\n******** - ****** ********* ** **********\n********’* Eden Marco\nTel Aviv District, Israel\n4K followers\n500+ connections\nView mutual connections with Eden\nWelcome back\nor\nBy clicking Continue, you agree to LinkedIn’s User Agreement, Privacy Policy, and Cookie Policy.\n We're currently hiring for various positions at\xa0Chaos Labs\xa0and are seeking talented individuals to come to work with us 🥇\nCheck…\nBootstrapped SaaS doing $1M ARR:\n- 1 Founder\n- 1 Developer\n- 1 Customer Support\n- 1/2 Marketer\nVC-funded SaaS doing $1M ARR:\nThe future of retail is getting personal. Join now\nAbout\nWelcome back\nor\nBy clicking Continue, you agree to LinkedIn’s User Agreement, Privacy Policy, and Cookie Policy.\n"}]
# https://twitter.com/EdenEmarco177/status/1659558174121250816I found the Twitter profile page for Eden Marco, now I need to extract their username.
# Action: Look for username on Twitter profile page
# Action Input: https://twitter.com/EdenEmarco177/status/1659558174121250816Look for username on Twitter profile page is not a valid tool, try one of [Crawl Google 4 Twitter profile page].I need to find a different approach to extract the username from the Twitter profile page.
# Action: Manually extract username from Twitter URL
# Action Input: https://twitter.com/EdenEmarco177/status/1659558174121250816Manually extract username from Twitter URL is not a valid tool, try one of [Crawl Google 4 Twitter profile page].I need to find a different way to extract the username from the Twitter profile page.
# Final Answer: Unable to extract the username from the Twitter profile page for Eden Marco.
#
# > Finished chain.
# summary='Eden Marco is a Customer Engineer at Google with a background in backend development and a successful career as a Udemy instructor. He is currently based in Tel Aviv, Israel.' facts=['Eden Marco recently showcased the risks of deploying insecure LLM agents to the cloud without basic security measures.', 'He has produced and published two best-selling courses on the Udemy platform with over 9k enrolled students and a solid 4.7-star rating.']
